const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || '/Users/well/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');

(async () => {
  const browser = await chromium.launch({headless: true, executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
  const page = await browser.newPage({viewport: {width: 1440, height: 1000}});
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('dialog', dialog => dialog.accept());
  const screenshots = fs.mkdtempSync(path.join(os.tmpdir(), 'series-browser-'));
  const origin = 'http://127.0.0.1:8874';
  try {
    await page.goto(origin);
    const setup = await page.request.post(`${origin}/api/setup`, {data: {username: 'series-test', password: 'synthetic-test-only'}});
    assert.equal((await setup.json()).ok, true);
    await page.reload();
    assert.equal(await page.locator('#data-group-modal').isHidden(), true);
    await page.locator('.store-card[data-account-id="2"]').click();
    await page.locator('.nav-series').click();
    await page.locator('#series-select option').filter({hasText: '单商品系列'}).waitFor({state: 'attached'});
    await page.locator('#series-start-date').fill('2026-10-08');
    await page.locator('#series-end-date').fill('2026-10-08');
    await page.locator('#series-select').selectOption({label: '单商品系列 · 1 个商品'});
    await page.waitForFunction(() => seriesBoardData?.business.gmv === 100);
    assert.equal(await page.locator('#series-rows tr').count(), 1);
    assert.match(await page.locator('#series-rows').innerText(), /100\.00/);
    await page.locator('#series-rows [data-product-id]').click();
    await page.waitForFunction(() => document.querySelector('#baby-coverage').textContent.includes('已读取经营数据'));
    assert.equal(await page.locator('#baby-start-date').inputValue(), '2026-10-08');
    assert.equal(await page.locator('#baby-end-date').inputValue(), '2026-10-08');
    assert.equal(await page.locator('#baby-product-id').innerText(), 'ID 919688715573');
    await page.locator('.nav-series').click();
    await page.locator('#series-select').selectOption({label: '多商品系列 · 2 个商品'});
    await page.waitForFunction(() => seriesBoardData?.business.gmv === 400);
    assert.equal(await page.locator('#series-rows tr').count(), 2);
    await page.locator('#series-data-group').selectOption({label: '推广数据组'});
    await page.waitForFunction(() => [...document.querySelectorAll('#series-group-metrics [data-metric]')].some(x => x.dataset.metric === 'roi'));
    await page.locator('#series-trend-metric').selectOption('spend');
    assert.equal(await page.locator('#series-trend circle').count(), 1);
    await page.screenshot({path: path.join(screenshots, 'desktop.png'), fullPage: true});
    await page.locator('#series-edit').click();
    await page.locator('#series-name').fill('已修改系列');
    await page.locator('#series-draft-members [data-remove="1027168958052"]').click();
    await page.locator('#series-save').click();
    await page.waitForFunction(() => seriesBoardData?.member_version === 2 && seriesBoardData?.business.gmv === 100);
    await page.locator('#series-version').selectOption('1');
    await page.waitForFunction(() => seriesBoardData?.member_version === 1 && seriesBoardData?.business.gmv === 400);
    assert.match(await page.locator('#series-scope').innerText(), /历史成员集合/);
    await page.reload();
    await page.locator('.nav-series').click();
    await page.locator('#series-select').selectOption({label: '已修改系列 · 1 个商品'});
    await page.locator('#series-start-date').fill('2026-10-08');
    await page.locator('#series-end-date').fill('2026-10-08');
    await page.locator('#series-refresh').click();
    await page.waitForFunction(() => seriesBoardData?.member_version === 2 && seriesBoardData?.business.gmv === 100);
    assert.equal(await page.locator('#series-data-group option:checked').innerText(), '推广数据组');
    await page.locator('#series-new').click();
    await page.locator('#series-name').fill('浏览器新建系列');
    await page.locator('#series-product-search').fill('919688715573');
    await page.locator('#series-product-results [data-add="919688715573"]').click();
    await page.locator('#series-add-id').click();
    await page.waitForFunction(() => document.querySelector('#series-editor-note').textContent.includes('已经在系列内'));
    await page.locator('#series-product-search').fill('999999999999999');
    await page.locator('#series-add-id').click();
    await page.waitForFunction(() => document.querySelector('#series-editor-note').textContent.includes('未找到'));
    await page.locator('#series-save').click();
    await page.waitForFunction(() => seriesBoardData?.series.name === '浏览器新建系列');
    await page.locator('#series-edit').click();
    await page.locator('#series-product-search').fill('1027168958052');
    await page.locator('#series-add-id').click();
    await page.waitForFunction(() => seriesDraft.length === 2);
    await page.locator('#series-save').click();
    await page.waitForFunction(() => seriesBoardData?.series.name === '浏览器新建系列' && seriesBoardData?.business.gmv === 400);
    await page.locator('#series-page .sortable[data-sort="spend"]').click();
    assert.match(await page.locator('#series-rows tr').first().innerText(), /919688715573/);
    await page.locator('#series-page .group-manage').click();
    assert.equal(await page.locator('#data-group-modal').isVisible(), true);
    await page.locator('#data-group-name').fill('系列自定义');
    for (const checkbox of await page.locator('#data-group-items input:not(:disabled)').all()) await checkbox.uncheck();
    await page.locator('#data-group-items [data-code="gmv"] input').check();
    await page.locator('#data-group-items [data-code="spend"] input').check();
    await page.locator('#data-group-save').click();
    await page.waitForFunction(() => document.querySelector('#series-data-group option:checked').textContent === '系列自定义');
    assert.equal(await page.locator('#series-group-metrics [data-metric]').count(), 2);
    await page.setViewportSize({width: 390, height: 844});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    assert.equal(await page.locator('#series-page .group-manage').evaluate(button => button.scrollHeight <= button.clientHeight), true);
    assert.equal(await page.locator('#series-page .plan-shell').evaluate(shell => shell.scrollWidth > shell.clientWidth), true);
    await page.evaluate(() => scrollTo(0, 0));
    await page.screenshot({path: path.join(screenshots, 'mobile.png'), fullPage: true});
    await page.locator('#series-edit').click();
    assert.equal(await page.evaluate(() => document.querySelector('#series-editor').getBoundingClientRect().right <= innerWidth), true);
    await page.screenshot({path: path.join(screenshots, 'mobile-editor.png'), fullPage: true});
    await page.locator('#series-delete').click();
    await page.waitForFunction(() => !seriesList.some(item => item.name === '浏览器新建系列'));
    await page.locator('.nav-home').click();
    await page.locator('.store-card[data-account-id="3"]').click();
    await page.locator('.nav-series').click();
    await page.waitForFunction(() => document.querySelector('#series-coverage').textContent.includes('尚未创建系列'));
    assert.equal(await page.locator('#series-rows [data-product-id]').count(), 0);
    assert.equal(await page.locator('#series-business-core').innerText(), '暂无数据');
    assert.deepEqual(errors, []);
    console.log(JSON.stringify({ok: true, screenshots, checks: 'single/multi/version/create/edit/delete/group/persistence/jump/isolation/desktop/mobile', errors}, null, 2));
  } finally {
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
